### ISSUE TITLE
sa-core package.json

### ISSUE THREAD

**Issue by poorsecretary** [median-dxz/seerh5-assistant#1]
seerh5-assistant/packages/core/package.json 的export 里不知道为什么路径都是relative to dist 文件夹的，但是core里面并没有这个文件夹，是不是之前有然后没改package.json啊。

**Comment by median-dxz** [comment]
这个的话，首先这个项目使用typescript写的，其次对于sa-core包，没有使用bundler，直接用tsc进行转译作为输出。
因此这个dist文件夹是执行tsc构建后的输出产物，需要先进行build。
具体详见[package.json](https://github.com/median-dxz/seerh5-assistant/blob/master/packages/core/package.json?plain=1)和[tsconfig.json](https://github.com/median-dxz/seerh5-assistant/blob/master/packages/core/tsconfig.json?plain=1)
