### ISSUE TITLE
给`launcher`的测试脚本加上`--host`

### ISSUE THREAD

**Issue by MengNianxiaoyao** [median-dxz/seerh5-assistant#16]
如题，本人电脑是经常开着代理的，如果测试脚本不加`--host`进行暴露，就会出现无法访问的情况

```
"dev": "vite --open"
```
改成
```
"dev": "vite --host --open"
```

**Comment by median-dxz** [comment]
1. 首先，这个不是测试脚本，这条命令的意思是启动vite的开发服务器，不是用于测试的。
2. 你的代理是怎么设置的，我不是很清楚。但是默认情况下，开发服务器只监听来自`localhost`的请求(即不加`--host`)，任何代理都不应该影响你从localhost访问开发服务器。根据vite的官方文档，除非你需要从非localhost访问开发服务器，才需要这个选项。
3. 如果你确定不是端口占用的话，可以具体描述一下无法访问情况，我可以帮忙排查一下。
4. 如果只是你自己有特殊需要，开发测试的时候自己把这个选项加上就行了。

**Comment by MengNianxiaoyao** [comment]
> 1. 首先，这个不是测试脚本，这条命令的意思是启动vite的开发服务器，不是用于测试的。
> 2. 你的代理是怎么设置的，我不是很清楚。但是默认情况下，开发服务器只监听来自`localhost`的请求(即不加`--host`)，任何代理都不应该影响你从localhost访问开发服务器。根据vite的官方文档，除非你需要从非localhost访问开发服务器，才需要这个选项。
> 3. 如果你确定不是端口占用的话，可以具体描述一下无法访问情况，我可以帮忙排查一下。
> 4. 如果只是你自己有特殊需要，开发测试的时候自己把这个选项加上就行了。

代理开启tun就会出现访问不了的情况，而且我能确定不是端口占用。但关闭tun开启系统代理就不会。

**Comment by median-dxz** [comment]
> 代理开启tun就会出现访问不了的情况，而且我能确定不是端口占用。但关闭tun开启系统代理就不会。

你的代理有开启允许局域网连接么？

**Comment by MengNianxiaoyao** [comment]
有

**Comment by median-dxz** [comment]
> 有

你可以把允许局域网连接关了试试，我平常用都是tun+系统代理，但是没有开允许局域网连接。

此外我说的具体描述一下访问不了，指的是你使用浏览器打开localhost:1234进行开发的时候，请求的具体情况。比如说，你使用F12打开开发者工具，在Network选下卡下是什么情况？vite的控制台输出又是什么情况？

**Comment by MengNianxiaoyao** [comment]
![Clip_2024-05-23_14-54-53](https://github.com/median-dxz/seerh5-assistant/assets/103258286/735c406a-170a-472e-9a74-95670959e5b6)
允许局域网连接关了也不行，tun+系统代理也是不行的，只能使用系统代理才能正常访问

**Comment by median-dxz** [comment]
那就比较奇怪了，vite的控制台输出呢？这个问题或许你应该去vite那边开个issue，你试试新建一个vite项目，看看会不会出现这个问题。这样能确定问题到底出在哪里。

**Comment by MengNianxiaoyao** [comment]
> 那就比较奇怪了，vite的控制台输出呢？这个问题或许你应该去vite那边开个issue，你试试新建一个vite项目，看看会不会出现这个问题。这样能确定问题到底出在哪里。

我这个应该算特殊情况了，我自己加个--host得了
