### ISSUE TITLE
[错误报告] 运行程序时出现 "Error: connect ECONNREFUSED ::1:80" 错误

### ISSUE THREAD

**Issue by poorsecretary** [median-dxz/seerh5-assistant#2]
**错误描述**
在尝试使用该程序时，我遇到了以下错误信息：

```
03:57:58 [vite] http proxy error at /seerh5.61.com/app.js?t=1686556678680:
Error: connect ECONNREFUSED ::1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```
**问题背景**
我尝试在我的环境中使用程序时遇到了这个错误。这个程序使用了 Vite 构建工具，并尝试在本地运行一个 HTTP 代理。

**错误详细信息**
错误信息中指出了错误的原因和位置。根据错误提示，这是一个连接被拒绝的错误 (ECONNREFUSED)，发生在本地主机 (::1) 的 80 端口上。

**问题重现步骤**
在我的环境中，安装了所需的依赖并克隆了程序的代码。
在终端中进入程序的根目录，并执行启动命令。
在启动过程中，出现了上述错误信息。
**期望行为**
我期望程序能够成功启动，并且 HTTP 代理能够正常工作，没有连接被拒绝的错误。

**环境信息**
操作系统：Windows 11 
Node.js 版本：v18.16.0
NPM：9v.7.1
其他相关软件或依赖的版本信息
**为了解决这个问题，我已经尝试了以下方法：**
检查本地主机和端口是否正确，并确保没有其他程序占用了该端口。
确认是否存在防火墙或网络代理的配置问题，导致连接被拒绝。

**Comment by median-dxz** [comment]
上个版本刚刚完成了后端的分离，你检查一下backend有没启动。
具体说的话，你看一眼`app/package.json`，要启动app需要先运行`npm run serve`再运行`npm run dev`

**Comment by median-dxz** [comment]
首页文档还没更新，我的锅

**Comment by median-dxz** [comment]
额外提醒一下，目前有许多信息是硬编码在`sa-app`的代码里的（这个问题在日程上），典型就是各种精灵的ct，以及当前周年庆签到用到的cookie等等。这个问题主要是因为我没有公开宣传过，大部分时间都是自用，所以才拖到现在没有解决。之后的版本的一个主要目标就是把用户配置全部分离到后端单独存储，方便新用户配置。
如果你现在想尝鲜的话，主要就是日任模块下面的data.ts，mod模块下的sign和petFragmentLevel（精灵因子），里面的内容都要先调整成自己的。
