### ISSUE TITLE
套装切换bug

### ISSUE THREAD

**Issue by alphabet0** [median-dxz/seerh5-assistant#24]
把漆黑天使切换为杰出新兵（自带目镜）后，再切换回漆黑天使，目镜那栏会显示异常，虽然改了，但不显示。
https://www.alipan.com/s/aJD77DELLAi

**Comment by median-dxz** [comment]
感谢反馈，我今天会去排查一下。

首先是两个小建议🤝：
1. github应该支持直接上传视频吧，编辑框下面有一个Paste, drop. or click to add files按钮。
2. 最近刚刚更新了launcher@0.9.0，你可以用git更新一下。

然后，为了帮助定位问题，可以提供一下你所用版本的commit hash吗？日志功能我计划在0.10.0版本中添加，到时候排查起问题会方便许多。但是现在还没有这个功能，因此我需要手动切换到你所用的commit，手动复现并调试来解决bug。

**Comment by median-dxz** [comment]
忘说了，0.9.0涉及模组改动，更新起来会麻烦一点，下面是具体的步骤清单，有问题欢迎随时提出。
1. 删除`server/mods`下所有文件（如有需要，可以备份data.json）
2. 删除`server/configs`下所有文件（同上，如果需要保存一些设置，自己手动备份一下相关文件，`sea-mods.json`和`sea-pets.json`不涉及用户配置，不需要备份）
3. 启动后端服务器
4. 在`sdk`下运行`pnpm build`
5. 进入游戏，现在支持在登录器中直接添加和编辑你的模组配置和任务配置。需要手动编辑json配置的地方，有不懂的可以问我。
6. 日任部分的对战方案现在不是内嵌的了，要在配置中添加，你可以探索一下，默认是空方案，无法运行。

**Comment by median-dxz** [comment]
我在最新的提交中（f7b2dcc）无法通过以下步骤复现问题：
1. 切换到一个带目镜的套装
2. 切换到一个不带目镜的套装
3. 此时目镜栏应显示为"空"，切换目镜
4. 目镜被正常切换

**Comment by alphabet0** [comment]
我用的是这个版本：27990208ced821bd36ca3a4015d10656d0df7301
然后f7b2dccca65de55e071c7e7d4cbe2c7f7ceae208这个版本我也试了，我感觉不好用。
原因如下：

1. 启动速度慢了，可能跟加载窗口有关
2. 最重要的，战斗速度不够快，对比官方h5没优势。2799020这个版本能鼠标连点放技能，很爽。

**Comment by median-dxz** [comment]
> 我用的是这个版本：27990208ced821bd36ca3a4015d10656d0df7301 然后f7b2dccca65de55e071c7e7d4cbe2c7f7ceae208这个版本我也试了，我感觉不好用。 原因如下：
> 
> 1. 启动速度慢了，可能跟加载窗口有关
> 2. 最重要的，战斗速度不够快，对比官方h5没优势。2799020这个版本能鼠标连点放技能，很爽。

一个一个问题来解决：

1. 这个issue本身的问题在 （ https://github.com/median-dxz/seerh5-assistant/commit/f7b2dccca65de55e071c7e7d4cbe2c7f7ceae208 ）解决了吗？
2. ServiceWorker的缓存每周过期一次，多次重启游戏后，加载速度还有变慢吗？新的Loading页面是纯粹显示目的，启动器初始化的逻辑本身没有改变。
3. 加速静态对战的逻辑已经从启动器的捆绑模组中移动到sdk的预设集中，你有重新构建并安装sdk中的模组吗？
![image](https://github.com/user-attachments/assets/938accb2-eb62-4de2-950b-4faa260cad12)

**Comment by median-dxz** [comment]
现在有人用了，我在考虑建个discord服务器方便快速沟通交流😂，既然能上github了，上dc应该也没啥问题吧。

**Comment by median-dxz** [comment]
如果还需要进一步反馈，可以请求重新打开该问题。

**Comment by alphabet0** [comment]
问题应该出在这了：

> 然后你需要分别为前端和sdk安装sea-core，由于各种因素的考虑，sea-core没有发布在npm上，因此你有两种选择：
> 
> 通过本地tarball包安装
> 通过远程tarball包安装
> 不过现阶段使用clone整个项目的方式来尝鲜的话，可以直接遵循下面步骤：

我没有sea-core

**Comment by median-dxz** [comment]
我可以看到你的邮件，但是找不到github上的评论...

方便的话加一下DC服务器吧，交流起来方便一点。那个tarball是本地包pack得到的。

https://discord.gg/Q7AJsEzSdN
