### ISSUE TITLE
日任掉线

### ISSUE THREAD

**Issue by median-dxz** [median-dxz/seerh5-assistant#28]
打勇者之塔会被掉线，搞不清检测机制了。。反正就是会掉线，加延迟也没用。不过允许重连，未来可能加上自动重连功能。

**Comment by alphabet0** [comment]
因子关卡打太快，会被强制下线。不过勇者之塔速度要快些。
会不会是日常也有限速？

**Comment by median-dxz** [comment]
> 因子关卡打太快，会被强制下线。不过勇者之塔速度要快些。 会不会是日常也有限速？

因子和日常的限速策略应该不是同一个。不过，最近好像没有出现掉线的情况了。
