### ISSUE TITLE
请问一下，有没有模组开发的接口文档

### ISSUE THREAD

**Issue by yourlies** [median-dxz/seerh5-assistant#30]
使用体验了一下大佬的项目，非常nb，科技改变生活啊，我想在此基础上额外开发一些mod，想请问下有什么能参考的吗

**Comment by yourlies** [comment]
我看漏了，好像还真有

**Comment by median-dxz** [comment]
> 我看漏了，好像还真有

有，但是不多也不全，更多还是得依靠你自己看项目代码的能力了😂，到明年我才会有空慢慢更新。

现在想了解模组开发的话，最好clone下项目，然后尝试自己阅读`sdk/mods/median`下的模组。

**Comment by median-dxz** [comment]
方便的话可以加一下dc群组，我主要在那边进行讨论和发布最新的更新内容
